/** Identidade pública ATLLY — Human Performance System (Command). */
export const brand = {
  name: "ATLLY",
  shortName: "ATLLY",
  legalName: "ATLLY Ltda.",
  category: "Human Performance System",
  tagline: "Human Performance System",
  commandLine: "Ative seu sistema. Treine com precisão.",
  socialLine: "Rede de atletas · Treino · Corrida · Performance",
  athlete: "Atleta",
  athletes: "Atletas",
  athleteProfile: "Identidade do atleta",
  athleteProfileHint: "Capa, bio, seguidores e suas publicações na rede.",
  profileSettings: "Configurações do perfil",
  profileSettingsHint: "Dados cadastrais usados em treinos e matrícula.",
  feedEmptyTitle: "Canal de performance",
  feedEmptyText: "Publique um treino, siga atletas ou finalize uma atividade na Corrida.",
  navAria: "Navegação ATLLY",
  menuAria: "Menu do atleta",
  areaEyebrow: "ATLLY Command",
  supportTeam: "Equipe ATLLY",
  shareSuffix: "na ATLLY",
  musicDefaultArtist: "ATLLY",
  playTitle: "Play ATLLY",
  codeLabel: "Código",
  followAthletes: "Seguir atletas",
  communityHint: "Conecte-se com outros atletas no Feed, Desafios e Corrida.",
  accessEyebrow: "Acesso ao sistema",
  loginTitle: "Entrar no sistema",
  registerTitle: "Ativar conta",
  loginCopy: "Identifique-se com e-mail, telefone ou Google.",
  registerCopy: "Defina objetivo e disponibilidade para liberar sua jornada."
} as const;
