/** Identidade pública ATLLY — Human Performance System. */
export const brand = {
  name: "ATLLY",
  shortName: "ATLLY",
  legalName: "ATLLY Ltda.",
  category: "Human Performance System",
  tagline: "Human Performance System",
  socialLine: "Rede social de atletas · Treino · Corrida · Performance",
  athlete: "Atleta",
  athletes: "Atletas",
  athleteProfile: "Perfil do atleta",
  athleteProfileHint: "Capa, bio, seguidores e suas publicações na rede.",
  profileSettings: "Configurações do perfil",
  profileSettingsHint: "Dados cadastrais usados em treinos e matrícula.",
  feedEmptyTitle: "Seu Feed começa aqui",
  feedEmptyText: "Publique um treino, siga atletas ou finalize uma corrida na aba Corrida.",
  navAria: "Navegação ATLLY",
  menuAria: "Menu do atleta",
  areaEyebrow: "ATLLY",
  supportTeam: "Equipe ATLLY",
  shareSuffix: "na ATLLY",
  musicDefaultArtist: "ATLLY",
  playTitle: "Play ATLLY",
  codeLabel: "Código",
  followAthletes: "Seguir atletas",
  communityHint: "Conecte-se com outros atletas no Feed, Desafios e Corrida."
} as const;
